### ISSUE TITLE
Slow `admm_MADMMplasso()` under `ADMMplasso()`

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#17]
It seems the C++ is now very slower than the R when I run with the example on  github   (setting p=500 and nlambda=50). I don't know wether it is due to the back and forth between  C++ and R for each lambda.
You can check this by calling the MADMMplasso function and set legacy=T or F (I have included this in the call).

_Originally posted by @Theo-qua in https://github.com/ocbe-uio/MADMMplasso/issues/16#issuecomment-1836414657_

**Comment by Theo-qua** [comment]
Dear Waldir,I think another factor could be how C++ is dealing with the task when p>N. Could you run the same example you sent with p=500, my_lambda = matrix(rep(2.3, dim(y)[2]), 1) and see the time difference. I think the problem occurs when p>N. I had the following results 

system.time( fit<-MADMMplasso(X,Z,y,alpha=alpha,my_lambda = matrix(rep(2.3, dim(y)[2]), 1),lambda_min=0.01,max_it=5000,e.abs=e.abs,e.rel=e.rel,maxgrid=1,nlambda = 1, rho=5,tree = TT,my_print = F,alph=1,parallel =F,pal=1,gg=gg1,tol=tol,cl=4 ,legacy=T) )Convergence reached after 41 iterationsTime difference of 13.84166 secs[1]  1.00000 14.00000  1.00000 20.21003   user  system elapsed  12.599   0.425  13.965 

system.time( fit<-MADMMplasso(X,Z,y,alpha=alpha,my_lambda = matrix(rep(2.3, dim(y)[2]), 1),lambda_min=0.01,max_it=5000,e.abs=e.abs,e.rel=e.rel,maxgrid=1,nlambda = 1, rho=5,tree = TT,my_print = F,alph=1,parallel =F,pal=1,gg=gg1,tol=tol,cl=4 ,legacy=F) )Time difference of 2.758352 mins[1]  1.00000 11.00000  3.00000 20.62792   user  system elapsed 163.759   0.619 165.662

We can look into it. I am also already working on the documentation.

Best regards,Theo



Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Monday, December 4, 2023 at 06:49:20 AM GMT+1, Waldir Leoncio ***@***.***> wrote:  
 
 


Can reproduce. See example below:
# Train the model
# generate some data
library(MADMMplasso)
set.seed(1235)
N <- 100
p <- 50
nz <- 4
K <- nz
X <- matrix(rnorm(n = N * p), nrow = N, ncol = p)
mx <- colMeans(X)
sx <- sqrt(apply(X, 2, var))
X <- scale(X, mx, sx)
X <- matrix(as.numeric(X), N, p)
Z <- matrix(rnorm(N * nz), N, nz)
mz <- colMeans(Z)
sz <- sqrt(apply(Z, 2, var))
Z <- scale(Z, mz, sz)
beta_1 <- rep(x = 0, times = p)
beta_2 <- rep(x = 0, times = p)
beta_3 <- rep(x = 0, times = p)
beta_4 <- rep(x = 0, times = p)
beta_5 <- rep(x = 0, times = p)
beta_6 <- rep(x = 0, times = p)

beta_1[1:5] <- c(2, 2, 2, 2, 2)
beta_2[1:5] <- c(2, 2, 2, 2, 2)
beta_3[6:10] <- c(2, 2, 2, -2, -2)
beta_4[6:10] <- c(2, 2, 2, -2, -2)
beta_5[11:15] <- c(-2, -2, -2, -2, -2)
beta_6[11:15] <- c(-2, -2, -2, -2, -2)

Beta <- cbind(beta_1, beta_2, beta_3, beta_4, beta_5, beta_6)
colnames(Beta) <- c(1:6)

theta <- array(0, c(p, K, 6))
theta[1, 1, 1] <- 2
theta[3, 2, 1] <- 2
theta[4, 3, 1] <- -2
theta[5, 4, 1] <- -2
theta[1, 1, 2] <- 2
theta[3, 2, 2] <- 2
theta[4, 3, 2] <- -2
theta[5, 4, 2] <- -2
theta[6, 1, 3] <- 2
theta[8, 2, 3] <- 2
theta[9, 3, 3] <- -2
theta[10, 4, 3] <- -2
theta[6, 1, 4] <- 2
theta[8, 2, 4] <- 2
theta[9, 3, 4] <- -2
theta[10, 4, 4] <- -2
theta[11, 1, 5] <- 2
theta[13, 2, 5] <- 2
theta[14, 3, 5] <- -2
theta[15, 4, 5] <- -2
theta[11, 1, 6] <- 2
theta[13, 2, 6] <- 2
theta[14, 3, 6] <- -2
theta[15, 4, 6] <- -2

library(MASS)
pliable <- matrix(0, N, 6)
for (e in 1:6) {
  pliable[, e] <- compute_pliable(X, Z, theta[, , e])
}

esd <- diag(6)
e <- MASS::mvrnorm(N, mu = rep(0, 6), Sigma = esd)
y_train <- X %*% Beta + pliable + e
y <- y_train

colnames(y) <- c(paste("y", 1:(ncol(y)), sep = ""))
TT <- tree_parms(y)
plot(TT$h_clust)

gg1 <- matrix(0, 2, 2)
gg1[1, ] <- c(0.02, 0.02)
gg1[2, ] <- c(0.02, 0.02)

nlambda <- 1
e.abs <- 1E-4
e.rel <- 1E-2
alpha <- .2
tol <- 1E-3

fit <- MADMMplasso(
  X, Z, y,
  alpha = alpha, my_lambda = matrix(rep(0.2, dim(y)[2]), 1),
  lambda_min = 0.001, max_it = 5000, e.abs = e.abs, e.rel = e.rel, maxgrid = nlambda,
  nlambda = nlambda, rho = 5, tree = TT, my_print = FALSE, alph = 1, parallel = FALSE,
  pal = 1, gg = gg1, tol = tol, cl = 6, legacy = FALSE
)
#> Using C++
#> Time difference of 2.135376 secs
#> [1]  1.000000 14.000000 29.000000  3.108636
fit_2 <- MADMMplasso(
  X, Z, y,
  alpha = alpha, my_lambda = matrix(rep(0.2, dim(y)[2]), 1),
  lambda_min = 0.001, max_it = 5000, e.abs = e.abs, e.rel = e.rel, maxgrid = nlambda,
  nlambda = nlambda, rho = 5, tree = TT, my_print = FALSE, alph = 1, parallel = FALSE,
  pal = 1, gg = gg1, tol = tol, cl = 6, legacy = TRUE
)
#> Warning in admm_MADMMplasso(beta0, theta0, beta, beta_hat, theta, rho1, : Using
#> legacy R code for MADMMplasso.This functionality will be removed in a future
#> release.Please consider using legacy = FALSE instead.
#> Convergence reached after 37 iterations
#> Time difference of 1.288508 secs
#> [1]  1.000000 14.000000 33.000000  1.417865
print(packageVersion("MADMMplasso"))
#> [1] '0.0.0.9008'
Created on 2023-12-04 with reprex v2.0.2

Since one call of the C++ version is much faster than the legacy, I agree with your suspicion that the back-and-forth is causing the slowdown. I'll perform some profiling and work on this ASAP.

**Comment by wleoncio** [comment]
Start by translating this loop into C++:

https://github.com/ocbe-uio/MADMMplasso/blob/062fd9e3e7cccc731e46bf25836732d97ff16d53/R/MADMMplasso.R#L233-L307

**Comment by wleoncio** [comment]
This was accidentally closed because I incorrectly linked PR #22 to this issue instead of #19. Reopening and starting work on it.

**Comment by wleoncio** [comment]
I've ran the `GDSC_clean.R` script on the `GDSC_BayesSUR_new.rds` data and got the following times after tweaking the last line of the script to match the calls on https://github.com/ocbe-uio/MADMMplasso/pull/29#issuecomment-1976204482 (1 run of each row):

`ncol(X)` | backend | elapsed (s)
--------:|-----------|----------:
100 | C++ | 287
100 | R | 273
300 | C++ | 2 364
300 | R | 641

So the C++ code is indeed _significantly_ slower than legacy for larger matrices. And this was on the `issue-17` branch, with the code for the `hh`-loop completely translated, which means the code needs further profiling to identify the bottleneck.

Regardless, I'll open a PR to merge the work done so far.

**Comment by wleoncio** [comment]
Just ran a profile on the smaller dataset (X with 100 columns), this is where `MADMMplasso()` spends most of its time, per engine (version 0.0.0.9016, tables were truncated at "t" for comparison):

# R

```

$by.total
                         total.time total.pct self.time self.pct
"MADMMplasso"               1284.94    100.00      0.02     0.00
"suppressMessages"          1284.94    100.00      0.00     0.00
"withCallingHandlers"       1284.94    100.00      0.00     0.00
"hh_nlambda_loop"           1284.12     99.94      0.00     0.00
"admm_MADMMplasso"          1280.44     99.65     42.74     3.33
"solve"                      804.40     62.60      4.28     0.33
"solve.default"              510.58     39.74    461.52    35.92
"%*%"                        330.80     25.74    328.30    25.55
"t"                          126.76      9.87     13.14     1.02
```

# C++

```
$by.total
                      total.time total.pct self.time self.pct
"MADMMplasso"            1369.90    100.00      0.00     0.00
"suppressMessages"       1369.90    100.00      0.00     0.00
"withCallingHandlers"    1369.90    100.00      0.00     0.00
".Call"                  1369.46     99.97   1369.46    99.97
"hh_nlambda_loop_cpp"    1369.46     99.97      0.00     0.00
"hh_nlambda_loop"        1369.46     99.97      0.00     0.00
"La.svd"                    0.32      0.02      0.32     0.02
"svd"                       0.32      0.02      0.00     0.00
"FUN"                       0.10      0.01      0.00     0.00
"t"                         0.10      0.01      0.00     0.00
```

So here's more evidence of the enormous cost of moving between R and C++ (as shown by the time taken in the `.Call()` function). I'm not sure why this is happening, since `hh_nlambda_loop_cpp()` is only called once, and that's the only connection from R to C++, right? I need some more time to look into this...

**Comment by wleoncio** [comment]
BTW, it seems like for the R code most of the time is spent inverting matrices, so if we could optimize that, that might make a huge difference in performance.

**Comment by Theo-qua** [comment]
I will also look into this. 

I agree with you. I have tried several ways to handle the matrix inverse and the current one seem to be the best I could find. I will read  more algebra papers to find other alternatives.

**Comment by Theo-qua** [comment]
I agree with you. Maybe we should have a short discussion after the easter break. I think the main problem will come from the matrix inversion and the part for obtaining E. I will look into that.

**Comment by wleoncio** [comment]
Hi Theo,

I've done a bit more work on this, and I think I've finally reached a point where the C++ code is outperforming R for matrices of any size. It's not a huge improvement, but it's an important milestone.

Using the GDSC example (see above), these are the results I am getting now:
```r
Benchmark X_mini
Unit: milliseconds
 expr       min        lq     mean   median       uq      max neval cld
    R 1397.2303 1564.5367 1732.632 1614.797 1931.378 2561.068    30  a 
  C++  979.6887  999.8709 1135.751 1044.650 1159.363 1707.716    30   b

Benchmark X
Unit: seconds
 expr      min       lq     mean   median       uq      max neval cld
    R 4.100515 4.223840 4.372278 4.422617 4.475534 4.543463    10  a 
  C++ 3.610225 3.618488 3.650130 3.634111 3.657458 3.790086    10   b
```

Can you observe similar results? Here's how to install the package version with the changes:

```r
remotes::install_github("ocbe-uio/MADMMplasso@issue-17")
```

Before testing, make sure you're running MADMMplasso version 0.0.0.9017-1716458578.

**Comment by Theo-qua** [comment]
Hello,This sounds good! I will check this today and give you my feedback. 



Best regards,Theo
 

    On Thursday, May 23, 2024 at 12:09:07 PM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 


Hi Theo,

I've done a bit more work on this, and I think I've finally reached a point where the C++ code is outperforming R for matrices of any size. It's not a huge improvement, but it's an important milestone.

Using the GDSC example (see above), these are the results I am getting now:
Benchmark X_mini
Unit: milliseconds
 expr       min        lq     mean   median       uq      max neval cld
    R 1397.2303 1564.5367 1732.632 1614.797 1931.378 2561.068    30  a 
  C++  979.6887  999.8709 1135.751 1044.650 1159.363 1707.716    30   b

Benchmark X
Unit: seconds
 expr      min       lq     mean   median       uq      max neval cld
    R 4.100515 4.223840 4.372278 4.422617 4.475534 4.543463    10  a 
  C++ 3.610225 3.618488 3.650130 3.634111 3.657458 3.790086    10   b
Can you observe similar results? Here's how to install the package version with the changes:
***@***.***")
Before testing, make sure you're running MADMMplasso version 0.0.0.9017-1716458578.

**Comment by Theo-qua** [comment]
Dear Waldir,
Sorry for  delaying in getting back to you. I have compared the two and yes, the C++ is now outperforming the R code. This is a good progress and I think we should be ready to submit it to CRAN since we have seen an improvement. 

I have noticed something from the plot function when using the call with C++. The one with the R did not give any error but I got an error after calling for the plot(fit). I will go through the plot function again to check reason but I wanted to draw your attention to it. 


Best regards,
Theo

**Comment by Theo-qua** [comment]
Hello,
There are two other things that need to be checked. The parallel call in MADMMplasso produces the following error for the C++ ;
Error in { : task 1 failed - "argument "CW" is missing, with no default"


And it produces the following for the R ;
Error in MADMMplasso(X, Z, y, alpha = alpha, my_lambda = NULL, lambda_min = 0.01,  : 
  object 'my_values' not found

I can see that the error in the R code is from line 219-223. The my_values was not predefined before line 219. 

Regarding the C++, I think it is becuse of how you call the admm_MADMMplasso_cpp. Could you please compare that to the call of hh_nlambda_loop_cpp

Best regards,
Theo

**Comment by wleoncio** [comment]
Thanks for checking, Theo!

> he parallel call in MADMMplasso produces the following error for the C++ ;
Error in { : task 1 failed - "argument "CW" is missing, with no default" And it produces the following for the R ;
Error in MADMMplasso(X, Z, y, alpha = alpha, my_lambda = NULL, lambda_min = 0.01, :
object 'my_values' not found

I'll take a look at this, haven't really tested the parallel option in the C++ code.

> I have noticed something from the plot function when using the call with C++. The one with the R did not give any error but I got an error after calling for the plot(fit). I will go through the plot function again to check reason but I wanted to draw your attention to it.

This looks like a separate issue, so I think I'll fix the first one, issue a PR for the merge, and handle this separately (after the merge).

**Comment by Theo-qua** [comment]
Thank you!

**Comment by wleoncio** [comment]
OK, so I fixed the R code for all combinations of `parallel` and `pal` (this should close #34 once merged). Also fixed the issues mentioned in the previous message regarding the C++ code. There are still two things to tackle:

1. The C++ results when `parallel` or `pal` are true don't match the ones when they're both false (in R, they all match)
2. Unit tests are now failing for `reg()`. No idea why, but needs to be investigated.

I haven't checked the `plot()` issue mentioned yet.

**Comment by Theo-qua** [comment]
Hello Waldir,
Thank you for the update. Could you please tell me which version is this. I just tried the issue 17 but run into error. 



Also, would it be possible for you to schedule a meeting so that we both go through  points 1 and 2 together. I think that would help us identify the problem quickly. 


Thank you again, 


Theo

**Comment by wleoncio** [comment]
Hi Theo,

The latest version on the issue-17 branch is numbered 0.0.0.9017-1719289199. To install it:

```r
remotes::install_github("ocbe-uio/OCBEdev")
```

(curiously enough, the parallel versions are taking forever on my home machine to run (they were quite fast on the work PC, which is much weaker. Let me know how it goes there)

The following test file can be run to reproduce point 1:

```r
source("tests/testthat/test-parallel.R")
```

Glad to meet, I'll send you an e-mail about it.

**Comment by wleoncio** [comment]
Update: the version number should match now (I had forgotten to push the version number update this morning). The codebase is otherwise identical, so the test files from my previous post should behave exactly the same.
