### ISSUE TITLE
Check some of the components of  new version with the old one 

### ISSUE THREAD

**Issue by Theo-qua** [ocbe-uio/MADMMplasso#28]
Hello Waldir,
Could we meet for a short time so that we check C++ functions (model_p.cpp, reg.cpp, model_intercept.cpp) you have included in the legacy=TRUE call. There seem to be something not working as it should. 

Please let me know which time will be best for you. Thank you.

Best regards,
Theo

**Comment by wleoncio** [comment]
Sure thing, I'll send you an invitation in a minute.

**Comment by Theo-qua** [comment]
Good

**Comment by wleoncio** [comment]
Last working version available here:

```r
remotes::install_github("ocbe-uio/MADMMplasso", ref="last-good-CRC")
```

So it looks like the error was introduced when I worked on PR #11.

**Comment by wleoncio** [comment]
Your suspicion was correct, Theo! The problem was introduced on commit d4e3ef1cfad96b7dc7f567929e6397badacd8bc7, when `reg()` was translated. The commit immediately before (4075e043eff936cd643f7ad4a1d87c6473e676c3), after `model_p()` and `model_intercept()` were translated, still work. To reproduce:

```r
library(remotes)
# CRC script works
install_github("ocbe-uio/MADMMplasso", ref="4075e043eff936cd643f7ad4a1d87c6473e676c3")
# CRC script breaks
install_github("ocbe-uio/MADMMplasso", ref="d4e3ef1cfad96b7dc7f567929e6397badacd8bc7")
```

then run `CRC_clean.R` (sent by e-mail, together with the dataset it uses).

**Comment by wleoncio** [comment]
Fixed! `reg()` was putting the slope of `new1` into `beta01`, not the intercept. I'll send in a PR soon.
